stages:
    - deploy

deploy_a:
    tags:
        - guacamole
    stage: deploy
    script:
        - echo "Copiamos backend a la crpeta html"
        - echo "$RootPass"
        - echo $RootPass
        - echo "$RootPass" | sudo -S cp -r WebForoUpna/backend/ /var/www/html/
        - sleep 5

deploy_b:
    tags:
        - guacamole
    stage: deploy
    script:
        - echo "Copiamo frontend a la carpeta html"
        - echo "$RootPass" | sudo -S cp -r WebForoUpna/frontend/ /var/www/html/
        - sleep 5